name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - additional_urls: https://arduino.esp8266.com/stable/package_esp8266com_index.json
            arduino-board: 'esp8266:esp8266@3.1.2'
            arduino-platform: 'esp8266:esp8266:nodemcuv2'
            build-property: 'build.defines="-DCI_TESTING -DESP8266"'
          - additional_urls: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            arduino-board: 'esp32:esp32@2.0.13'
            arduino-platform: 'esp32:esp32:esp32'
            build-property: 'build.defines=-DCI_TESTING'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install platform
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls ${{ matrix.additional_urls }}
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-board }}
      - name: Install dependencies
        run: |
          arduino-cli lib install "NTPClient@3.2.1"
          arduino-cli lib install "ArduinoJson@6.21.3"
          arduino-cli lib install "Websockets@2.4.0"
          arduino-cli lib install "DHTNEW@0.4.18"
          arduino-cli lib install "OneButton@2.1.0"
      - name: Compile sketch
        run: arduino-cli compile --build-property ${{ matrix.build-property }} --fqbn ${{ matrix.arduino-platform }} ./autowatering/autowatering.ino
