name: CI

on:
  push:
    branches:
      - 'master'
      - 'dev'
  pull_request:
  release:
    types: [published]

env:
  arduino-platform: 'esp8266:esp8266:nodemcuv2'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install platform
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install ${{ env.arduino-platform }}
      - name: Compile Sketch
        run: arduino-cli compile --build-property "build.extra_flags=-DENABLE_DEBUG" --fqbn ${{ env.arduino-platform }} .\autowatering-esp8266\autowatering-esp8266.ino
