name: CI

on:
  push:
    branches:
      - 'master'
      - 'dev'
  pull_request:
  release:
    types: [published]

env:
  arduino-board: 'esp8266:esp8266@3.0.2'
  arduino-platform: 'esp8266:esp8266:nodemcuv2'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install platform
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install ${{ env.arduino-board }}
      - name: Install dependencies
        run: |
          arduino-cli lib install "NTPClient@3.2.0"
          arduino-cli lib install "ArduinoJson@6.18.3"
          arduino-cli lib install "PubSubClient@2.8.0"
          arduino-cli lib install "DHTstable@1.0.1"
          arduino-cli lib install "OneButton@2.0.1"
      - name: Compile sketch
        run: arduino-cli compile --build-property "build.extra_flags=-DCI_TESTING" --fqbn ${{ env.arduino-platform }} ./autowatering-esp8266/autowatering-esp8266.ino
